version: '3'

vars:
  DOCKER_IMAGE: kazhuravlev/serve-spa

tasks:
  build:docker:
    desc: Build docker image
    cmds:
      - |
        docker buildx build \
          --platform=linux/amd64 \
          -f Dockerfile \
          -t {{ .DOCKER_IMAGE }} \
          .
